name: My first GitHub workflow
run-name: First workflow # Optional

# Events triggering the workflow
on: [push]

# Group of jobs to run as poart of the workflow
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"