name: My first GitHub workflow
run-name: First workflow # Optional
permissions: {}

# Events triggering the workflow
on: [push]

# Group of jobs to run as poart of the workflow
jobs:
  greet:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - run: echo "Hello world"

  run-code:
    needs: checks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13", "3.14" ]
        os: [ "macos-latest", "windows-latest", "ubuntu-latest" ]
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - run: python mycode.py

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: "Run tests"
        run: pytest